In [1]:
import numpy
arr = numpy.array([1,2,3,4,5])
print(arr)

import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
[1 2 3 4 5]
<class 'numpy.ndarray'>


In [14]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('last element from 2nd dim:',arr[1,-3])



last element from 2nd dim: 8


In [16]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:6])


[2 3 4 5 6]


In [22]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[-3:-1])

[5 6]


In [23]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2])

[2 4]


In [24]:
import numpy as np
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [28]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr.dtype)

int32


In [32]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0]=42
print(arr)
print(x)
arr1 = np.array([1,2,3,4,5])
x1 = arr.view()
arr1[0]=42
print(arr1)
print(x1)
print(x.base)
print(x1.base)

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]
None
[42  2  3  4  5]


In [33]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [34]:
import numpy as np
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print('shape of array:',arr.shape)

[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


In [37]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [38]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [40]:
import numpy as np
arr = np.array([1,2,3,4,5])
for x in arr:
    print(x)

1
2
3
4
5


In [41]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)
    for x in arr:
        for y in x:
            print(y)

[1 2 3]
1
2
3
4
5
6
[4 5 6]
1
2
3
4
5
6


In [46]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.array([7,8,9])
arr = np.concatenate((arr1,arr2,arr3))
print(arr)

[1 2 3 4 5 6 7 8 9]


In [51]:
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr = np.concatenate((arr1,arr2),axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [2]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.stack((arr1,arr2),axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [54]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.hstack((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [55]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


In [56]:
import numpy as np
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr = np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [57]:
import numpy as np
arr = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
newarr = np.array_split(arr,3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [58]:
#searching an array
import numpy as np
arr = np.array([1,2,3,4,5,4,4])
x = np.where(arr == 4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [59]:
#sorting of an array
import numpy as np
arr = np.array([3,2,0,1])
print(np.sort(arr))

[0 1 2 3]


In [61]:
#getting some elements in existing array
import numpy as np
arr = np.array([41,42,43,44])
x = [True,False,True,False]
newarr = arr[x]
print(newarr)

[41 43]


In [62]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target
Feature_names = iris.feature_names
target_names = iris.target_names
print("Feature names",Feature_names)
print("Target names",target_names)
print("\n first 10 rows of X:\n",X[:10])

Feature names ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names ['setosa' 'versicolor' 'virginica']

 first 10 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]
