In [1]:
import numpy as np
arr = np.array([1,2,3,4])
print(arr.dtype)


int32


In [12]:
import numpy as np
arr = np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [16]:
#shape of an array
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)

(2, 4)


In [15]:
import numpy as np
arr = np.array([1,2,3,4,5])
x = arr.copy()
arr[0] = 42
print(arr)
print(x)
arr1 = np.array([1,2,3,4,5])
x1 = arr.view()
arr1[0] = 42
print(arr1)
print(x1)
print(x.base)
print(x1.base)

[42  2  3  4  5]
[1 2 3 4 5]
[42  2  3  4  5]
[42  2  3  4  5]
None
[42  2  3  4  5]


In [17]:
import numpy as np
arr = np.array([1,2,3,4],ndmin=5)
print(arr)
print('shape of array:',arr.shape)

[[[[[1 2 3 4]]]]]
shape of array: (1, 1, 1, 1, 4)


In [22]:
#reshaping means changing the shape of an array
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [23]:
#2d to 3d
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
for x in arr:
    print(x)
for x in arr:
    for y in x:
        print(y)

[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [1]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target
Feature_names = iris.feature_names
target_names = iris.target_names
print("Feature names",Feature_names)
print("Target names",target_names)
print("\n first 10 rows of X:\n",X[:10])

Feature names ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target names ['setosa' 'versicolor' 'virginica']

 first 10 rows of X:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]]


In [3]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size = 0.4,random_state=1)
from sklearn.neighbors import KNeighborsClassifier 
from sklearn import metrics
classifier_knn = KNeighborsClassifier(n_neighbors = 3)
classifier_knn.fit(X_train, y_train)
y_pred = classifier_knn.predict(X_test)
#finding accuracy by comparing actual response values(y_test)with predicted response value(y_pred)
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))
#provoding sample data and the model will make prediction out of that data
sample=[[5,5,3,2],[2,4,3,5]] 
preds = classifier_knn.predict(sample)
pred_species = [iris.target_names[p] for p in preds]
print("predictions:",pred_species)

Accuracy: 0.9833333333333333
predictions: ['versicolor', 'virginica']


In [2]:
from sklearn.datasets import load_iris
iris = load_iris()
X = iris.data
y = iris.target
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split( X,y,test_size = 0.1,random_state = 1)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(135, 4)
(15, 4)
(135,)
(15,)
